name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'  # Adjust based on your version

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform code
        run: terraform fmt 

      - name: Validate Terraform code
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  ansible:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook for Autoscaling
        run: |
          ansible-playbook -i inventory/hosts playbook_ansible_autoscaling.yml

  website:
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Website Deployment Script
        run: bash Git-Script.sh

  notify:
    runs-on: ubuntu-latest
    needs: website

    steps:
      - name: Notify success
        run: echo "Deployment Successful"
